plugin_repo:
  type: resource
  name: data/plugins.json
  metadata_provider:
    type: pylon.core.providers.metadata.http
  source_provider:
    type: pylon.core.providers.source.git
    delete_git_dir: false
    depth: null

preordered_plugins:
  - security
  - theme
  - secrets
  - artifacts
  - backend_performance
  - integrations
  - security_scanner_qualys
  - security_scanner_zap
  - processing_severity_filter
  - reporter_email
  - reporter_jira
  - scheduling
  - auth_mappers
